const mongoose = require("mongoose");


const assetlistSchema  = new mongoose.Schema({
    name: { type: String, default: "" },
    assetitlistsdate: { type: Date, default: null },
    assetid: { type: String, default: "" },
    assetitlistscompany: { type: [String], default: "" },
    computername: { type: String, default: "" },
    device: { type: [String], default: "" },
    devicetype: { type: [String], default: "" },
    devicechoice: { type: [String], default: "" },
    devicemodel: { type: String, default: "" },
    devicesn: { type: String, default: "" },
    cpu: { type: [String], default: "" },
    cputype: { type: [String], default: "" },
    cpuassetaccountno: { type: String, default: "" },
    speed: { type: [String], default: "" },
    harddisk: { type: [String], default: "" },
    ram: { type: [String], default: "" },
    img: { type: String, default: "" },
    romdrive: { type: [String], default: "" },
    romdrivetype: { type: [String], default: "" },
    romsn: { type: String, default: "" },
    romassetid: { type: String, default: "" },
    monitor: { type: [String], default: "" },
    monitortype: { type: [String], default: "" },
    monitorsn: { type: String, default: "" },
    monitorassetid: { type: String, default: "" },
    keyboard: { type: [String], default: "" },
    keyboardtype: { type: [String], default: "" },
    keyboardsn: { type: String, default: "" },
    keyboardassetid: { type: String, default: "" },
    mouse: { type: [String], default: "" },
    mousetype: { type: [String], default: "" },
    mousesn: { type: String, default: "" },
    mouseassetid: { type: String, default: "" },
    printer: { type: [String], default: "" },
    printertype: { type: [String], default: "" },
    printermodel: { type: String, default: "" },
    printersn: { type: String, default: "" },
    printerassetid: { type: String, default: "" },
    ups: { type: [String], default: "" },
    upstype: { type: [String], default: "" },
    upsva: { type: [String], default: "" },
    upstypemodel: { type: String, default: "" },
    upstypesn: { type: String, default: "" },
    upstypeassetid: { type: String, default: "" },
    adaptor: { type: [String], default: "" },
    adaptorsn: { type: String, default: "" },
    other1: { type: String, default: "" },
    othersn: { type: String, default: "" },
    os: { type: [String], default: "" },
    ostype: { type: [String], default: "" },
    ossn: { type: String, default: "" },
    office: { type: [String], default: "" },
    officetype: { type: [String], default: "" },
    officesn: { type: String, default: "" },
    antivirus: { type: [String], default: "" },
    pdf: { type: [String], default: "" },
    utility: { type: [String], default: "" },
    other2: { type: String, default: "" },
    mapdrive: { type: String, default: "" },
    addprinter: { type: String, default: "" },
    other3: { type: String, default: "" },
    assetitlistsremark: { type: String, default: "" },
    dept: { type: String, default: "" },
    deliverydate:{ type: Date, default: null },


     repairs: [{ type: mongoose.Schema.Types.ObjectId, ref: "repair" }],
    
})
module.exports = mongoose.model("assetlist",assetlistSchema)
